---
- hosts: all
  become: yes

  tasks:
    - name: Update APT
      ansible.builtin.apt:
        update_cache: yes

    - name: Install python-apt and apache2 packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - python-apt
        - apache2

    - name: Copy apache.conf to /etc/apache2/sites-available/
      ansible.builtin.copy:
        src: files/config/apache.conf
        dest: /etc/apache2/sites-available/apache.conf
        owner: root
        group: root
        mode: 0644

    - name: Copy index.html to /var/www/html/
      ansible.builtin.copy:
        src: files/site/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

    - name: Create symbolic link for apache.conf
      ansible.builtin.file:
        src: /etc/apache2/sites-available/apache.conf
        dest: /etc/apache2/sites-enabled/apache.conf
        state: link
