---
- hosts: all
  become: yes
  tasks:
    - name: Update APT
      ansible.builtin.apt:
        update_cache: true
    - name: Install apache2
      ansible.builtin.apt:
        name: apache2
        state: present
    - name: Copy apache.conf
      ansible.builtin.copy:
        src: files/config/apache.conf
        dest: /etc/apache2/apache2.conf
        owner: root
        group: root
        mode: '0644'
    - name: Copy index.html
      ansible.builtin.copy:
        src: files/site/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
    - name: Create symbolic link
      ansible.builtin.file:
        src: /etc/apache2/apache2.conf
        dest: /etc/apache2/sites-enabled/000-default.conf
        state: link
    - name: Restart Apache service
      ansible.builtin.service:
        name: apache2
        state: restarted

